URHO_DIR=/cvs/Urho3D
OBJSHARPIE_BIN=/cvs/ObjectiveSharpie//llvm/_install/bin

SOURCES =	\
	generated/Animatable.cs		\
	generated/AnimatedModel.cs	\
	generated/AnimatedSprite2D.cs	\
	generated/Animation.cs		\
	generated/Animation2D.cs	\
	generated/AnimationController.cs\
	generated/AnimationSet2D.cs	\
	generated/AnimationState.cs	\
	generated/Application.cs	\
	generated/AsyncLoadState.cs	\
	generated/AttributeAccessor.cs	\
	generated/AttributeAnimationInfo.cs\
	generated/Audio.cs		\
	generated/BillboardSet.cs	\
	generated/BlendMode.cs		\
	generated/BodyType2D.cs		\
	generated/BorderImage.cs	\
	generated/BufferedSoundStream.cs\
	generated/Button.cs		\
	generated/Camera.cs		\
	generated/CheckBox.cs		\
	generated/CollisionBox2D.cs	\
	generated/CollisionChain2D.cs	\
	generated/CollisionCircle2D.cs	\
	generated/CollisionEdge2D.cs	\
	generated/CollisionPolygon2D.cs	\
	generated/CollisionShape2D.cs	\
	generated/CompareMode.cs	\
	generated/Component.cs		\
	generated/CompressedFormat.cs	\
	generated/Connection.cs		\
	generated/Console.cs		\
	generated/ConstantBuffer.cs	\
	generated/Constraint2D.cs	\
	generated/ConstraintDistance2D.cs\
	generated/ConstraintFriction2D.cs\
	generated/ConstraintGear2D.cs	\
	generated/ConstraintMotor2D.cs	\
	generated/ConstraintMouse2D.cs	\
	generated/ConstraintPrismatic2D.cs\
	generated/ConstraintPulley2D.cs	\
	generated/ConstraintRevolute2D.cs\
	generated/ConstraintRope2D.cs	\
	generated/ConstraintWeld2D.cs	\
	generated/ConstraintWheel2D.cs	\
	generated/Context.cs		\
	generated/Corner.cs		\
	generated/CreateMode.cs		\
	generated/CrowdAgent.cs		\
	generated/CrowdAgentState.cs	\
	generated/CrowdTargetState.cs	\
	generated/CubeMapFace.cs	\
	generated/CubeMapLayout.cs	\
	generated/CullMode.cs		\
	generated/Cursor.cs		\
	generated/CursorShape.cs	\
	generated/CustomGeometry.cs	\
	generated/DebugHud.cs		\
	generated/DebugRenderer.cs	\
	generated/DecalSet.cs		\
	generated/DeferredLightPSVariation.cs	\
	generated/DeferredLightVSVariation.cs	\
	generated/DetourCrowdManager.cs	\
	generated/Drawable.cs		\
	generated/Drawable2D.cs		\
	generated/DropDownList.cs	\
	generated/DynamicNavigationMesh.cs\
	generated/EmitterType.cs	\
	generated/EmitterType2D.cs	\
	generated/Engine.cs		\
	generated/FONT_TYPE.cs		\
	generated/FaceCameraMode.cs	\
	generated/File.cs		\
	generated/FileMode.cs		\
	generated/FileSelector.cs	\
	generated/FileSystem.cs		\
	generated/FileWatcher.cs	\
	generated/FillMode.cs		\
	generated/FocusMode.cs		\
	generated/Font.cs		\
	generated/FontFace.cs		\
	generated/FontFaceBitmap.cs	\
	generated/FontFaceFreeType.cs	\
	generated/FrustumPlane.cs	\
	generated/Geometry.cs	\
	generated/GeometryType.cs	\
	generated/Graphics.cs	\
	generated/HighlightMode.cs	\
	generated/HorizontalAlignment.cs	\
	generated/Image.cs	\
	generated/IndexBuffer.cs	\
	generated/Input.cs	\
	generated/InterpMethod.cs	\
	generated/InterpolationMode.cs	\
	generated/Intersection.cs	\
	generated/LayoutMode.cs	\
	generated/Light.cs	\
	generated/LightPSVariation.cs	\
	generated/LightType.cs	\
	generated/LightVSVariation.cs	\
	generated/LineEdit.cs	\
	generated/ListView.cs	\
	generated/LoadMode.cs	\
	generated/LockState.cs	\
	generated/Log.cs	\
	generated/LogicComponent.cs	\
	generated/LoopMode2D.cs	\
	generated/Material.cs	\
	generated/Menu.cs	\
	generated/MessageBox.cs	\
	generated/Model.cs	\
	generated/MouseMode.cs	\
	generated/NavArea.cs	\
	generated/Navigable.cs	\
	generated/NavigationMesh.cs	\
	generated/NavigationPushiness.cs	\
	generated/NavigationQuality.cs	\
	generated/NavmeshPartitionType.cs	\
	generated/Network.cs		\
	generated/Node.cs		\
	generated/Object.cs		\
	generated/ObjectAnimation.cs	\
	generated/ObjectFactory.cs	\
	generated/Obstacle.cs		\
	generated/OcclusionBuffer.cs	\
	generated/Octree.cs		\
	generated/OffMeshConnection.cs	\
	generated/OggVorbisSoundStream.cs	\
	generated/Orientation.cs	\
	generated/Orientation2D.cs	\
	generated/PListFile.cs		\
	generated/PListValueType.cs	\
	generated/PackageFile.cs	\
	generated/ParticleEffect.cs	\
	generated/ParticleEffect2D.cs	\
	generated/ParticleEmitter.cs	\
	generated/ParticleEmitter2D.cs	\
	generated/Pass.cs	\
	generated/PassLightingMode.cs	\
	generated/PhysicsWorld2D.cs	\
	generated/PrimitiveType.cs	\
	generated/Profiler.cs	\
	generated/PropertySet2D.cs	\
	generated/RayQueryLevel.cs	\
	generated/RefCount.cs	\
	generated/RefCounted.cs	\
	generated/RenderCommandSortMode.cs	\
	generated/RenderCommandType.cs	\
	generated/RenderPath.cs	\
	generated/RenderSurface.cs	\
	generated/RenderSurfaceUpdateMode.cs	\
	generated/RenderTargetSizeMode.cs	\
	generated/Renderer.cs	\
	generated/Renderer2D.cs	\
	generated/Resource.cs	\
	generated/ResourceCache.cs	\
	generated/ResourceRequest.cs	\
	generated/ResourceRouter.cs	\
	generated/RigidBody2D.cs	\
	generated/Scene.cs	\
	generated/ScrollBar.cs	\
	generated/ScrollView.cs	\
	generated/Serializable.cs	\
	generated/Shader.cs	\
	generated/ShaderParameterAnimationInfo.cs	\
	generated/ShaderParameterGroup.cs	\
	generated/ShaderPrecache.cs	\
	generated/ShaderProgram.cs	\
	generated/ShaderType.cs	\
	generated/ShaderVariation.cs	\
	generated/Skybox.cs	\
	generated/Slider.cs	\
	generated/SmoothedTransform.cs	\
	generated/Sound.cs	\
	generated/SoundListener.cs	\
	generated/SoundSource.cs	\
	generated/SoundSource3D.cs	\
	generated/SoundStream.cs	\
	generated/SplinePath.cs	\
	generated/Sprite.cs	\
	generated/Sprite2D.cs	\
	generated/SpriteSheet2D.cs	\
	generated/State.cs	\
	generated/StaticModel.cs	\
	generated/StaticModelGroup.cs	\
	generated/StaticSprite2D.cs	\
	generated/StencilOp.cs	\
	generated/Technique.cs	\
	generated/Terrain.cs	\
	generated/TerrainPatch.cs	\
	generated/Text.cs	\
	generated/Text3D.cs	\
	generated/TextEffect.cs	\
	generated/Texture.cs	\
	generated/Texture2D.cs	\
	generated/Texture3D.cs	\
	generated/TextureAddressMode.cs	\
	generated/TextureCoordinate.cs	\
	generated/TextureCube.cs	\
	generated/TextureFilterMode.cs	\
	generated/TextureUnit.cs	\
	generated/TextureUsage.cs	\
	generated/Tile2D.cs	\
	generated/TileMap2D.cs	\
	generated/TileMapLayer2D.cs	\
	generated/TileMapLayerType2D.cs	\
	generated/TileMapObject2D.cs	\
	generated/TileMapObjectType2D.cs	\
	generated/Time.cs	\
	generated/TmxFile2D.cs	\
	generated/TmxImageLayer2D.cs	\
	generated/TmxLayer2D.cs	\
	generated/TmxObjectGroup2D.cs	\
	generated/TmxTileLayer2D.cs	\
	generated/ToolTip.cs	\
	generated/TransformSpace.cs	\
	generated/TraversalMode.cs	\
	generated/Type.cs	\
	generated/UI.cs	\
	generated/UIElement.cs	\
	generated/UnknownComponent.cs	\
	generated/UpdateGeometryType.cs	\
	generated/ValueAnimation.cs	\
	generated/ValueAnimationInfo.cs	\
	generated/VariantType.cs	\
	generated/VertexBuffer.cs	\
	generated/VertexElement.cs	\
	generated/VertexLightVSVariation.cs	\
	generated/VerticalAlignment.cs	\
	generated/View.cs	\
	generated/View3D.cs	\
	generated/Viewport.cs	\
	generated/Window.cs	\
	generated/WindowDragMode.cs	\
	generated/WorkItem.cs	\
	generated/WorkQueue.cs	\
	generated/WrapMode.cs	\
	generated/XMLFile.cs	\
	generated/Zone.cs	\
	src/AttributeInfo.cs		\
	src/Object.cs			\
	src/RefCounted.cs		\
	src/StringHash.cs		\
	src/Stubs.cs			\
	src/Structs.cs

all: Urho.pch Urho.dll

run: gen-bind Urho.dll

gen-bind: Urho.pch ../SharpieBinder/bin/Debug/SharpieBinder.exe
	/mono/bin/mono ../SharpieBinder/bin/Debug/SharpieBinder.exe

Urho.dll: $(SOURCES) Makefile 
	mcs -unsafe -out:Urho.dll -target:library -debug $(SOURCES)


Urho.pch: AllUrho.h Makefile
	$(OBJSHARPIE_BIN)/clang -cc1 -emit-pch -o Urho.pch all-urho.cpp  -I$(URHO_DIR)/include -I$(URHO_DIR)/include/kNet

check-links:
	cd runtime; make check-links

../SharpieBinder/bin/Debug/SharpieBinder.exe: ../SharpieBinder/CxxBinder.cs ../SharpieBinder/Program.cs
	(cd ../SharpieBinder; xbuild)
